In [1]:
from dandi.dandiapi import DandiAPIClient

dandiset_id = '000041'  # ephys dataset from the Svoboda Lab
filepath = 'sub-BWRat17/sub-BWRat17_ses-BWRat17-121712_ecephys.nwb'  # 1.5GB file
with DandiAPIClient() as client:
    asset = client.get_dandiset(dandiset_id, 'draft').get_asset_by_path(filepath)
    s3_url = asset.get_content_url(follow_redirects=1, strip_query=True)

In [2]:
s3_url

'https://dandiarchive.s3.amazonaws.com/blobs/52c/d33/52cd33fc-1a16-46f2-9c1d-4f9f1b621f3c'

In [3]:
dandiset_id, filepath="0000041","sub-BWRat17/sub-BWRat17_ses-BWRat17-121712_ecephys.nwb"
from pynwb import NWBHDF5IO
from nwbwidgets import nwb2widget

io = NWBHDF5IO(s3_url,mode='r',load_namespaces=True,driver='ros3')
nwb = io.read()
nwb2widget(nwb)

/opt/conda/lib/python3.10/site-packages/xarray/backends/cfgrib_.py:29: UserWarning: Failed to load cfgrib - most likely there is a problem accessing the ecCodes library. Try `import cfgrib` to get the full error message
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/hdmf/spec/namespace.py:531: UserWarning: Ignoring cached namespace 'hdmf-common' version 1.1.3 because version 1.5.1 is already loaded.
  warn("Ignoring cached namespace '%s' version %s because version %s is already loaded."
/opt/conda/lib/python3.10/site-packages/hdmf/spec/namespace.py:531: UserWarning: Ignoring cached namespace 'core' version 2.2.5 because version 2.5.0 is already loaded.
  warn("Ignoring cached namespace '%s' version %s because version %s is already loaded."


In [4]:
nwb.units.to_dataframe()

global_id  shank_id   cell_type region  \
id                                           
0           1         0  excitatory    CTX   
1           2         0  excitatory    CTX   
2           3         1  excitatory    CTX   
3           4         2  excitatory    CTX   
4           5         3  excitatory    CTX   
5           6         4  excitatory    CTX   
6           7         5  excitatory    CTX   
7           8         6  excitatory    CTX   
8           9         7  excitatory    CTX   
9          10         8  excitatory    CTX   
10         11         9  inhibitory    CTX   
11         12        10  excitatory    CTX   
12         13        11  excitatory    CTX   
13         14        12  excitatory    CTX   
14         15         0  inhibitory    CTX   
15         16         1  excitatory    CTX   
16         17         2  excitatory    CTX   
17         18         3  excitatory    CTX   
18         19         4  excitatory    CTX   
19         20         0  excitatory    CTX   
20         21         1  excitatory    CTX   
21         22         2  inhibitory    CTX   
22         23         0  excitatory    CTX   
23         24         1  excitatory    CTX   
24         25         2  excitatory    CTX   
25         26         0  excitatory    CTX   
26         27         1  excitatory    CTX   
27         28         2  excitatory    CTX   
28         29         3  excitatory    CTX   
29         30         0  excitatory    CTX   
30         31         1  excitatory    CTX   
31         32         2  excitatory    CTX   
32         33         3  excitatory    CTX   
33         34         4  excitatory    CTX   
34         35         5  excitatory    CTX   
35         36         6  excitatory    CTX   
36         37         7  excitatory    CTX   
37         38         8  excitatory    CTX   
38         39         0  excitatory    CTX   
39         40         1  inhibitory    CTX   
40         41         2  excitatory    CTX   
41         42         3  excitatory    CTX   
42         43         4  excitatory    CTX   
43         44         5  excitatory    CTX   
44         45         6  excitatory    CTX   
45         46         7  excitatory    CTX   
46         47         8  inhibitory    CTX   
47         48         9  inhibitory    CTX   
48         49        10  excitatory    CTX   
49         50        11  excitatory    CTX   

                                      electrode_group  \
id                                                      
0   shank1 pynwb.ecephys.ElectrodeGroup at 0x14009...   
1   shank2 pynwb.ecephys.ElectrodeGroup at 0x14009...   
2   shank2 pynwb.ecephys.ElectrodeGroup at 0x14009...   
3   shank2 pynwb.ecephys.ElectrodeGroup at 0x14009...   
4   shank2 pynwb.ecephys.ElectrodeGroup at 0x14009...   
5   shank2 pynwb.ecephys.ElectrodeGroup at 0x14009...   
6   shank2 pynwb.ecephys.ElectrodeGroup at 0x14009...   
7   shank2 pynwb.ecephys.ElectrodeGroup at 0x14009...   
8   shank2 pynwb.ecephys.ElectrodeGroup at 0x14009...   
9   shank2 pynwb.ecephys.ElectrodeGroup at 0x14009...   
10  shank2 pynwb.ecephys.ElectrodeGroup at 0x14009...   
11  shank2 pynwb.ecephys.ElectrodeGroup at 0x14009...   
12  shank2 pynwb.ecephys.ElectrodeGroup at 0x14009...   
13  shank2 pynwb.ecephys.ElectrodeGroup at 0x14009...   
14  shank3 pynwb.ecephys.ElectrodeGroup at 0x14009...   
15  shank3 pynwb.ecephys.ElectrodeGroup at 0x14009...   
16  shank3 pynwb.ecephys.ElectrodeGroup at 0x14009...   
17  shank3 pynwb.ecephys.ElectrodeGroup at 0x14009...   
18  shank3 pynwb.ecephys.ElectrodeGroup at 0x14009...   
19  shank4 pynwb.ecephys.ElectrodeGroup at 0x14009...   
20  shank4 pynwb.ecephys.ElectrodeGroup at 0x14009...   
21  shank4 pynwb.ecephys.ElectrodeGroup at 0x14009...   
22  shank5 pynwb.ecephys.ElectrodeGroup at 0x14009...   
23  shank5 pynwb.ecephys.ElectrodeGroup at 0x14009...   
24  shank5 pynwb.ecephys.ElectrodeGroup at 0x14009...   
25  shank6 pynwb.ecephys.ElectrodeGroup at 0x14009...   
26  shank6 pynw

In [26]:
nwb.units["spike_times"][1]

array([4.27500000e-02, 6.13000000e-02, 2.06700000e-01, ...,
       6.04139040e+03, 6.04307445e+03, 6.05458580e+03])

In [67]:
nwb.units["cell_type"][:]=="excitatory"

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True, False, False,  True,  True])

In [106]:
import numpy

spiketrain=numpy.zeros(len(nwb.units["spike_times"]))
outputspiketrain=numpy.zeros(len(nwb.units["spike_times"]))


for i in range(len(nwb.units["spike_times"])):
    #print(i)
    spiketrain[i] = numpy.histogram(nwb.units["spike_times"][i], 
                         bins = 1, 
                         range = (0, 2))[0]/2
    
    outputspiketrain[i] = numpy.histogram(nwb.units["spike_times"][i], 
                         bins = 1, 
                         range = (2, 4))[0]/2


# select only excitatory neurons & firing rate not equal to zero   

spiketrainN=spiketrain[(nwb.units["cell_type"][:]=="excitatory") & ((spiketrain>0) | (outputspiketrain>0))]
outputspiketrainN=outputspiketrain[(nwb.units["cell_type"][:]=="excitatory") & ((spiketrain>0) | (outputspiketrain>0))]

    

In [108]:
outputspiketrainN

array([0.5, 0.5, 0.5, 0. , 0.5, 0.5, 3.5, 0.5, 0.5, 0.5, 2. , 0.5, 0. ,
       1. , 1. , 0.5, 0.5, 2. , 0. , 3. , 6.5, 0.5, 4. , 0.5, 1. , 0.5,
       2.5, 1. , 0. , 2. ])

In [85]:
selectid=nwb.units["id"][(nwb.units["cell_type"][:]=="excitatory")]

spiketime=nwb.units["spike_times"][selectid]
spiketime[10]

#selectid=nwb.units["id"][(nwb.units["cell_type"][:]=="excitatory"
#spiketime=nwb.units["spike_times"][selectid]


array([1.70150000e-01, 1.89950000e-01, 3.35100000e-01, ...,
       6.05836120e+03, 6.05838265e+03, 6.05849705e+03])

In [ ]:
#1. remove neurons with low firing rate
#2. get data from different "state" <- GLM model to calculate the connectivity P(t)=
#3. 

In [13]:
import fsspec
import pynwb
import h5py
from fsspec.implementations.cached import CachingFileSystem

# first, create a virtual filesystem based on the http protocol and use
# caching to save accessed data to RAM.
fs = CachingFileSystem(
    fs=fsspec.filesystem("http"),
    cache_storage="nwb-cache",  # Local folder for the cache
)

# next, open the file
with fs.open(s3_url, "rb") as f:
    with h5py.File(f) as file:
        with pynwb.NWBHDF5IO(file=file,load_namespaces=True, mode='r') as io:
            nwbfile = io.read()
            print(nwbfile.acquisition['lick_times'].time_series['lick_left_times'].data[:])


TypeError: NWBHDF5IO.__init__: missing argument 'path'

In [ ]:
from pynwb import NWBHDF5IO



In [27]:
!pwd

/home/jovyan
